### ISSUE TITLE
VB Core Crashes on Vulkan

### ISSUE THREAD

**Issue by shinra358** [libretro/beetle-vb-libretro#15]
Retroarch crashes when loading a game with the VB core under the vulkan backend.

**Comment by hizzlekizzle** [comment]
I can't reproduce this. Loads up just fine with Win64 latest nightly and fresh pull of the core from the online updater.

**Comment by shinra358** [comment]
Might be related to this because I'm using the same shader: https://github.com/libretro/beetle-psx-libretro/issues/155#issuecomment-277014943

**Comment by hizzlekizzle** [comment]
Nope, no problem with those shader presets. Your GPU could be running out of memory or something, though, /shrug

**Comment by shinra358** [comment]
Hmm, i have a 980m and it has 8gb of vram. I also have 32gb of memory ram
of corsair vengeance. My system doesnt slow down so i dunno if it could be
that @.@
