### ISSUE TITLE
Runs too Slow, unplayable on the 3DS (Both New 3DS and Old)

### ISSUE THREAD

**Issue by Cee123** [libretro/beetle-vb-libretro#32]
Beetle vb runs at only 19 fps on New Nintendo 3DS, even when overclocking is enabled.

**Comment by gingerbeardman** [comment]
Set core options CPU to fast to get a reasonable performance boost

**Comment by LibretroAdmin** [comment]
Invalid issue report, we cannot guarantee a baseline level of performance on 3DS. If it runs too slow, it is what it is for now.
