### ISSUE TITLE
Update core to 1.23.0

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-vb-libretro#45]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 0.9.36.1, they supposedly were not added.

After 0.9.36.1 there are several changes that would be good to include in the core to improve emulation.

- VB: Made (better) use of exceptions in the ROM image loading and initialization code.
- VB:  Corrected the value that the timer reload register is initialized with on reset.
- VB: Migrated debugger functions VBDBG_GetRegister() and VBDBG_SetRegister() over to the newer-style interface that takes integer IDs instead of std::string.
- VB: Replaced endian-handling functions local to vip.cpp with new code in endian.h derived from code written for Saturn emulation.
- VB: Fixed a regression introduced in 0.9.39.2 that caused transient sound/note distortion on save state load.
- VB: Finally commented out some debug printf()s.
- VB: Added support for custom palettes.
- VB: Reworked how LED on-state duration is translated into RGB values and added setting "vb.ledonscale"; the default value of "vb.ledonscale" is set such that the overall brightness will be lower than in previous versions of Mednafen, to reduce white crush, but the user can set it to a value of "1.9921875" to approximate the old brightness level.
- VB: Added the ability to toggle the state of the low battery sensor bit; configure the device on virtual input port 2(e.g. ALT+SHIFT+2) to assign a key/button to this function.

I comment as you recommended to me to be reflected and appear as a pending task.

Many thanks for your work.

**Comment by f21red** [comment]
There was enough stuff missing here also.
https://github.com/libretro/beetle-vb-libretro/pull/47

**Comment by ToniBC** [comment]
Thank you very much for updating it.
