### ISSUE TITLE
(Regression) Runs too slow on the Wii/Wii U

### ISSUE THREAD

**Issue by Cee123** [libretro/beetle-vb-libretro#48]
Suddenly this core is running far too slow on the Wii when it never used to. Not really sure what the problem is. It's also too slow on the New 3DS overclocked.

**Comment by f21red** [comment]
Yeah, it took like a 40% nosedive. I've got a few ideas to look into but it could be the new FPU and Exception handler code it uses.

**Comment by twinaphex** [comment]
That's pretty bad to hear. We really need to be on the lookout for this whenever somebody sends a commit updating code from an upstream version. We need to try to retain performance. If it's not possible, we need to perhaps create a separate core meant for platforms where the current mainline version cannot run at fullspeed. Upstream might not care about these older platforms, but we do.

**Comment by Cee123** [comment]
> 
> 
> Yeah, it took like a 40% nosedive. I've got a few ideas to look into but it could be the new FPU and Exception handler code it uses.

Oh ok. It may just be something small but who knows. I'm glad it's not just me then and that others have noticed the same thing. Good to know at least.

**Comment by Cee123** [comment]
> 
> 
> That's pretty bad to hear. We really need to be on the lookout for this whenever somebody sends a commit updating code from an upstream version. We need to try to retain performance. If it's not possible, we need to perhaps create a separate core meant for platforms where the current mainline version cannot run at fullspeed. Upstream might not care about these older platforms, but we do.

Absolutely. So true.

**Comment by f21red** [comment]
Checked mednafen-endian but compiler is smart enough to optimise it. Which leaves this one:
https://github.com/toufy/beetle-vb-libretro/blob/master/mednafen/hw_cpu/v810/v810_oploop.inc#L85

Upstream Mednafen turns this on for most non-msvc compilers so I'll try figuring out how to flip the switch and see where we go. Reuse some old files if needed (thank you github!).

**Comment by f21red** [comment]
Nothing budges the number. Upstream changed from "native float" to "int64" math, which must explain the problem as I've tried other tweaks.

**Comment by Cee123** [comment]
Is there anywhere we can download the older version of the core? The one that worked well without the framedrops.

**Comment by tryal-star** [comment]
Older versions:
http://buildbot.libretro.com/nightly/nintendo/wii/
http://buildbot.libretro.com/nightly/nintendo/wiiu/

Did the FP math really damage the speed that badly? If it's guilty, I'm wondering if some macro can be installed like FP_FAST that will use the old files. Maybe I'll try this myself since the hit is painful.

**Comment by Cee123** [comment]
That's no good. That only goes back to about a month ago.

I tried earliest nightly 1.7.8 version from 16/09/2019 but the issue is still there and seems to have been there for quite a long time without anyone noticing.

**Comment by tryal-star** [comment]
Wii test
2019-01-03 core
2019-11-14 retroarch
http://s000.tinyupload.com/index.php?file_id=08503984831439140149

**Comment by Cee123** [comment]
I'll try that version. Thanks heaps!

I also found a Spanish website with older versions but I had to translate it using Google
https://wii.scenebeta.com/noticia/retroarch-wii

**Comment by Cee123** [comment]
> 
> 
> Wii test
> 2019-01-03 core
> 2019-11-14 retroarch
> http://s000.tinyupload.com/index.php?file_id=08503984831439140149

Excellent! Thanks very much. I can confirm that version you sent runs at the proper speed.

**Comment by tryal-star** [comment]
Great! Here's the next one from 2019-05-26
http://s000.tinyupload.com/index.php?file_id=07660863519468334414

If this runs slow, go to options and set "CPU emulation" from "accurate" to "fast". Close Game. Load game. And try again.

**Comment by Cee123** [comment]
Thanks! That seems to work as well. It did run slow at first, so I set it from "accurate" to "fast" and then I saved the core overrides so it keeps that setting for all the games.

**Comment by Cee123** [comment]
Wonder if that option would also work on the 3DS.

**Comment by tryal-star** [comment]
3ds for 05-26
http://s000.tinyupload.com/index.php?file_id=83870838786344457142

I'll try compiling 05-30 for 3ds and wii when I get a chance.

**Comment by Cee123** [comment]
I kept that first version for the Wii, the second one was good but for some reason felt like it was running on frameskip.

**Comment by Cee123** [comment]
> 
> 
> 3ds for 05-26
> http://s000.tinyupload.com/index.php?file_id=83870838786344457142
> 
> I'll try compiling 05-30 for 3ds and wii when I get a chance.

Thanks! I'll try that one out on the 3DS as well.

**Comment by tryal-star** [comment]
05-30 both
http://s000.tinyupload.com/index.php?file_id=02234904961456673138

You can try fast-forward to see max fps.

**Comment by Cee123** [comment]
Thank you heaps. I'll try those ones out too.

**Comment by tryal-star** [comment]
Weird thing is for Wii
01-03-2019 = fullspeed

05-26-2019 = not much changed other than accurate flag
https://github.com/libretro/beetle-vb-libretro/commit/1bdd3a0ec30bc4bd4e98bd64594ccdf16291ce98

But you're getting some stuttering on 05-26 which I can't explain from the changelog. I'll look at it some more because I'm still interested.

**Comment by Cee123** [comment]
It's interesting. But I don't know if there is that big a difference between the fast setting on 05-26-2019 and the regular speed on 01-03-2019. But it does feel a bit like it's frame skipping as opposed to running that speed normally. I don't know, I could just be imagining it.

**Comment by tryal-star** [comment]
Could be possible it dips once a while. Compiler has to predict between fast and accurate now. Before it was always fast and could throw away unused parts of code. Wii is more sensitive to forced inline code and such.

Is there a way to play nice? I might try churning out something to verify.

**Comment by Cee123** [comment]
Well, I've tried the latest versions of the core and everything seems to working again on the Wii now.

**Comment by Cee123** [comment]
Whatever you guys have done with the latest versions, it's working fine now. It doesn't have the slowdowns anymore. I'll close this.
