### ISSUE TITLE
Virtual Boy games core dump on PS Vita

### ISSUE THREAD

**Issue by dekay** [libretro/beetle-vb-libretro#51]
I am a relatively new user of Retroarch on the Vita.  All the cores I've tried are working for me except Virtual Boy.  The two games I have tried (Nester's Funky Bowling and Wario Land) both cause Retroarch to core dump.  The earlier 1.8.2 version crashed as well.  I get nothing but a black screen before the crash happens.  A zip of the core file is attached from 1.8.3.  Hopefully this is enough to go on.

[psp2core-1578840623-0x0000293339-mednafen_vb_libretro.self.psp2dmp.uncompressed.zip](https://github.com/libretro/beetle-vb-libretro/files/4050783/psp2core-1578840623-0x0000293339-mednafen_vb_libretro.self.psp2dmp.uncompressed.zip)

**Comment by r-type** [comment]
caused by memset on wrong surface
https://github.com/libretro/beetle-vb-libretro/blob/master/mednafen/vb/vip.cpp#L918

should be  surface->pixels16 instead of  surface->pixels for vita

#if defined(WANT_32BPP)
	  memset(surface->pixels, 0, 768 * 448 * 4);
#elif defined(WANT_16BPP)
	  memset(surface->pixels16, 0, 768 * 448 * 2);
#endif
