### ISSUE TITLE
[Feature Request] Reverse side-by-side mode

### ISSUE THREAD

**Issue by wickjames086** [libretro/beetle-vb-libretro#52]
I would love it if there was a setting to use side-by-side mode but with the left screen on the right and the right screen on the left.

I use Retroarch on my Nvidia Shield TV. Playing VB on a big TV is pretty neat, but there is a way that it could sort of support 3D. If the side-by-side mode had flipped screens, you could cross your eyes and "merge" the screens, resulting in fully enjoyable 3D effect. It pretty much works now, except the current side-by-side results in an inverted 3D effect when using my eye-cross method.

If this was implemented I would definitely be inclined to donate to the patreon.

**Comment by hizzlekizzle** [comment]
Whether you donate or not, this is a simple slang shader that can flip them:

```
#version 450

layout(push_constant) uniform Push
{
	vec4 SourceSize;
	vec4 OriginalSize;
	vec4 OutputSize;
	uint FrameCount;
} params;

layout(std140, set = 0, binding = 0) uniform UBO
{
	mat4 MVP;
} global;

#pragma stage vertex
layout(location = 0) in vec4 Position;
layout(location = 1) in vec2 TexCoord;
layout(location = 0) out vec2 vTexCoord;

void main()
{
   gl_Position = global.MVP * Position;
   vTexCoord = TexCoord;
}

#pragma stage fragment
layout(location = 0) in vec2 vTexCoord;
layout(location = 0) out vec4 FragColor;
layout(set = 0, binding = 2) uniform sampler2D Source;

void main()
{
   vec2 flipcoord = vTexCoord.xy;
   flipcoord.x = (vTexCoord.x > 0.5) ? vTexCoord.x - 0.5 : vTexCoord.x + 0.5;
   FragColor = vec4(texture(Source, flipcoord).rgb, 1.0);
}
```

**Comment by wickjames086** [comment]
Would you believe me if I said I had no idea how to implement that?

**Comment by hizzlekizzle** [comment]
Ok, here are slang and glsl shaders and presets for it:
http://www.mediafire.com/file/p0nndmq0718sdbq/flip-eye-shaders.zip
Download that and put the resulting folder into your 'shaders' folder, then go to quick menu > shaders > load shader preset and load it (it'll only show the one that's appropriate for your current video driver)

**Comment by wickjames086** [comment]
Thank you so much for making it easy :)

I’m just a simple man who wants to play Vertical Force.

**Comment by hizzlekizzle** [comment]
dang, $50 :O That wasn't necessary, but we definitely appreciate it. Hope you have fun with the 3D-ness :)
