### ISSUE TITLE
Is it possible to fix speed in the PS Vita core?

### ISSUE THREAD

**Issue by noradninja** [libretro/beetle-vb-libretro#55]
This core seems to run at ~half speed (24-30FPS) on the Vita. I realize it’s probably not a priority, but given that it’s powerful enough to emulate N64 fairly well, I’m surprised it doesn’t run VB at fullspeed.

**Comment by LibretroAdmin** [comment]
Invalid issue report, we cannot guarantee a baseline level of performance on PS Vita. If it runs too slow, it is what it is for now.
