### ISSUE TITLE
Android/Shaders Black Screen/Virtual Boy

### ISSUE THREAD

**Issue by SkimmingSanshiro** [libretro/beetle-vb-libretro#6]
Im sorry guys if my searching was inadequate also for the messy report, but im using the nightly from 8/3 1.2.2 but have had this problem on mobile for a year now
And the im trying to apply the gameboy shader but it has no effect on the virtual boy core

Galaxy S5 4.2.2 Att Snapdragon
-recreate
-Try to apply shader to virtualboy core
-save application of shaders
-Tried all passes
-black screen

I googled around when I first had a problem almost a year ago. and it seem like its maybe a known issue.

Thanks guys

just a note you can get a b/w "filter" by setting the core options to palette b/w from b/r in the quick menu. BUt i wish to try my hand at stereoscopic modification of the side-by-side.cg

**Comment by mhaze618** [comment]
Im not sure you guys should recreate, but I managed to get Sidebyside.glsl going! Not sure if you can close this topic, Ive still had issue with the gameboy filter...
im going to muddle throught this to try implement 3D but this will be my first project of any technical sort 
 http://janstechblog.blogspot.com/2012/06/emulating-virtual-boy-on-3d-tv.html

**Comment by twinaphex** [comment]
Sounds interesting. Also, we have a board dedicated to shaders on our website's forums page, you might want to check that out and see if they can help you with the problems youv'e been having with certain shaders/filters.

**Comment by mhaze618** [comment]
narrowed it down to I need access to the .cfg file. but I connot find it for the life of me the one that has what the pc version has here
http://i.imgur.com/iWrxASp.jpg

ive looked sdcard/android/data and data/data/.comretroarch niether has one. the former has similar things but not whats mentioned here\
http://janstechblog.blogspot.com/2012/06/emulating-virtual-boy-on-3d-tv.html

**Comment by mhaze618** [comment]
I have found the file however im not sure the core supports the edits. the file is in data/android/.com.retroarch
and is name retroarch.cores.cfg
I think the core does not support it?

http://janstechblog.blogspot.com/2012/06/emulating-virtual-boy-on-3d-tv.html

it only has 2 options with underscores instead of underslash, im going to para phrase
vb_anaglyph_mode = "red and blue"
vb_Palatte_mode = " Black and white"

i add what she says bi\ut with under slashes to no effect

**Comment by hizzlekizzle** [comment]
I answered this on the shader subforum, but I'll post here just for reference. The other 3D methods aren't hooked up in the libretro port currently and are stubbed as 'todo; complicated'. In the meantime, I whipped up a shader that takes the anaglyph image and separates it into side-by-side with some runtime parameters to control eye separation, vertical position and zoom factor.

**Comment by mhaze618** [comment]
Your second revision works great, seems to render small and overrides the black and white palatte is the only thing

http://imgur.com/a/VHCBh

I can't get the gameboy pocket shader to work, but I did get mcgreen from the /misc to work, I ran it as only 1 pass, I think is the resolution problem.

http://imgur.com/HUBY0Zj

I hope the lenses of Google cardboard work wel

**Comment by hizzlekizzle** [comment]
Cool :)

It's designed for use with the red/cyan anaglyph palette, and it does make everything red, but I can make that optional. I'll post any changes on the forum.

**Comment by mhaze618** [comment]
So still a of a issue. Getting some mild to game breaking horizontal lines on only the left eye
http://imgur.com/5BhELc1

**Comment by hizzlekizzle** [comment]
That was an issue with clamping behavior. I added some checks to the shader to deal with that. It's posted in the thread on the forum.

Let me know if that gets you fixed up.

**Comment by LibretroAdmin** [comment]
Don't see how this has anything to do with the core, closing...
