### ISSUE TITLE
[3DS] Core is very laggy on New 3DS

### ISSUE THREAD

**Issue by UltraSyko** [libretro/beetle-vb-libretro#60]
I have noticed improvements over the years. I remember it used to crash on boot. But now it's a steady 15fps. Was wondering if it can be more optimized like the massive picodrive 3ds upgrades

**Comment by gingerbeardman** [comment]
In core options you can set CPU to "fast" (default is "accurate") to get reasonable performance boost. 

Also turn off music in-game can help if you don't mind not having music. 

In RetroArch turning off audio completely,  and other options, could be another way to increase performance.

**Comment by Syko7956** [comment]
It's the same performance, unfortunately. It was worth a shot

**Comment by gingerbeardman** [comment]
What game are you playing?

I was playing VB Golf last night and it runs with less lag when CPU is set to fast (compared to accurate)

**Comment by Syko7956** [comment]
The Wario game

**Comment by LibretroAdmin** [comment]
Invalid issue report, we cannot guarantee a baseline level of performance on 3DS. If it runs too slow, it is what it is for now.
