### ISSUE TITLE
[Feature Request] Toggle low battery signal

### ISSUE THREAD

**Issue by KR155E** [libretro/beetle-vb-libretro#63]
Since 1.22.0-UNSTABLE, Mednafen supports toggling the state of the low battery sensor bit with the W button, which is a neat feature for homebrew developers.

The Beetle VB core has been updated to 1.23.0 with https://github.com/libretro/beetle-vb-libretro/issues/45, but as far as I can tell, the low battery toogle is not wired up to libretro and not available in RetroArch.

Would love to see it supported. :-)

**Comment by negativeExponent** [comment]
there should only be 1-bit needed for this to happen, but, how to test for  this and which button should this be mapped to?

**Comment by KR155E** [comment]
I'd stick to the Mednafen key binding and map the function to the W button by default.

If it helps with testing, I can create a quick test ROM that shows a low battery indicator when the respective flag is set. Let me know.

**Comment by negativeExponent** [comment]
sent PR, assigning button X or Y as the trigger. See if this is enough for whatever its needed for...

**Comment by RokkumanX** [comment]
Nice work, looks really good.

Now, might I ask what that battery icon does? Does it show how much battery that is left on a wireless controller or heck even the laptop battery?

**Comment by KR155E** [comment]
Fantastic, thank you @negativeExponent! Does this work as a toggle or do you have to keep the button pressed for the indicator to appear? Toggle would be best.

@RokkumanX - The Virtual Boy is powered from either an AC adapter or a battery pak attached to the back of the controller. Alongside regular button presses, the controller sends a low battery status bit to the head unit. So if the Virtual Boy is running on batteries and these are getting low on power, that status bit will be 1. It's then up to the game to display the indicator you see in the above screenshot. Being able to toggle the status bit manually is of no value to the end user, but is quite useful for homebrew developers to implement such indicator.

**Comment by RokkumanX** [comment]
Thank you very much for the explanation!

**Comment by KR155E** [comment]
I was able to test the feature on the online emulator today and it works as expected. Thanks again!

**Comment by negativeExponent** [comment]
ok forgot about adding the key to input so it can be remapped. ill deal with later if no one else does ahead of me by then... i may need then to just assign one button for it.

**Comment by KR155E** [comment]
Sorry for reviving this old thread, but I tried remapping the input for the low battery toggle from a config file and it does not seem to work. I tried remapping the following value: input_player1_x_btn. Is this the wrong one?
